{% set name = "uwsift" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d0d717271a1b52da2a7638e7113160f813eb63f79f4ba85146deecd979ad5d6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - donfig
    - h5py
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - netcdf4
    - numba
    - numpy
    - pillow
    - pygrib  # [not win]
    - pyproj
    - pyshp
    - pyqt >=5.9
    - pyqtgraph
    - pyyaml
    - rasterio
    - satpy
    - scikit-image
    - shapely
    - sqlalchemy
    - vispy >=0.7.1

test:
  imports:
    - uwsift

about:
  home: http://sift.ssec.wisc.edu/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A visualization application for satellite imagery
  description: |
    Satellite Information Familiarization Tool (SIFT) was designed by the Space
    Science and Engineering Center (SSEC) at the University of
    Wisconsin - Madison to support scientists during forecaster training
    events. It provides a graphical interface for visualization and basic
    analysis of geostationary satellite data.
  doc_url: https://github.com/ssec/sift/wiki
  dev_url: https://github.com/ssec/sift

extra:
  recipe-maintainers:
    - djhoese
    - rayg-ssec
