{% set name = "uwsift" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4b18c616861f65079c25c1d9a35dbd9546871e49dbfa7f174d382dcbe35b276

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - donfig
    - h5py
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - netcdf4
    - numba
    - numpy
    - pillow
    - pygrib  # [not win]
    - pyproj
    - pyshp
    - pyqt >=5.9
    - pyqtgraph
    - pyyaml
    - rasterio
    - satpy
    - scikit-image
    - shapely
    - sqlalchemy
    - vispy >=0.6,<0.7

test:
  imports:
    - uwsift

about:
  home: http://sift.ssec.wisc.edu/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: A visualization application for satellite imagery
  description: |
    Satellite Information Familiarization Tool (SIFT) was designed by the Space
    Science and Engineering Center (SSEC) at the University of
    Wisconsin - Madison to support scientists during forecaster training
    events. It provides a graphical interface for visualization and basic
    analysis of geostationary satellite data.
  doc_url: https://github.com/ssec/sift/wiki
  dev_url: https://github.com/ssec/sift

extra:
  recipe-maintainers:
    - djhoese
    - rayg-ssec
